lapzone/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "cart"
urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="cart/detail.html"),
        name="detail",
    ),
    path("add/", views.CartAddView.as_view()),
    path("update/", views.CartUpdateView.as_view()),
    path("remove/", views.CartRemoveView.as_view()),
]

lapzone/customer/urls.py
from django.urls import path

from . import views


app_name = "customer"
urlpatterns = [
    path("", views.CustomerDetailView.as_view(), name="detail"),
    path("wish-list/", views.CustomerWishListView.as_view(), name="wish_list"),
    path("update/", views.CustomerUpdateView.as_view(), name="update"),
    path("delete/", views.CustomerDeleteView.as_view(), name="delete"),
]

lapzone/lapzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from general.error_views import (
    CustomBadRequestView,
    CustomPermissionDeniedView,
    CustomNotFoundView,
)


handler400 = CustomBadRequestView.as_view()
handler403 = CustomPermissionDeniedView.as_view()
handler404 = CustomNotFoundView.as_view()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("profile/", include("customer.urls")),
    path("mailing/", include("mailing.urls")),
    path(
        "faq/",
        TemplateView.as_view(template_name="pages/FAQs.html"),
        name="faq",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="pages/feedback.html"),
        name="feedback",
    ),
]

if settings.DEBUG and not settings.TESTING:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

lapzone/customer/forms.py
from django import forms
from django.contrib.auth.models import User

from general.forms import get_field_widget_attrs_with_placeholder_


class UserModelForm(forms.ModelForm):
    """Form for the User model."""

    def __init__(self, *args, **kwargs) -> None:
        """Initializes the UserModelForm."""
        super().__init__(*args, **kwargs)
        self.fields["username"].help_text = ""
        self.fields["first_name"].required = False
        self.fields["last_name"].required = False

    class Meta:
        """Meta options for the UserModelForm."""

        model = User
        fields = ["username", "first_name", "last_name"]
        widgets = {
            "username": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("Username")
            ),
            "first_name": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("First name")
            ),
            "last_name": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("Last name")
            ),
        }

lapzone/customer/views.py
from typing import Any
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models.query import QuerySet
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect

from shop.models import Like
from general.views import BaseView, DeleteViewMixin
from .forms import UserModelForm


class CustomerDetailView(BaseView, LoginRequiredMixin, generic.TemplateView):
    """View for the customer detail page."""

    template_name = "customer/detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Adds the UserModelForm to the context and returns it."""
        context: dict[str, Any] = super().get_context_data(**kwargs)
        context["form"] = UserModelForm(instance=self.request.user)
        return context


class CustomerWishListView(BaseView, LoginRequiredMixin, generic.ListView):
    """View for the customer wish list page."""

    paginate_by = 12
    template_name = "customer/wish_list.html"

    def get_queryset(self) -> QuerySet[Like]:
        """Returns the current user's wish list."""
        return self.request.user.like_set.all()


class CustomerPOSTViewMixin(BaseView):
    """Mixin for the "Customer" app POST views."""

    http_method_names = ["post"]

    def get_object(self, queryset: QuerySet[User] | None = None) -> User:
        """Returns the current user."""
        return self.request.user


class CustomerUpdateView(CustomerPOSTViewMixin, generic.UpdateView):
    """View to handle the UserModelForm and update the customer data."""

    model = User
    form_class = UserModelForm
    success_url = reverse_lazy("customer:detail")

    def form_valid(self, form: UserModelForm) -> HttpResponse:
        """Adds a success message and returns the super method."""
        messages.success(
            self.request, "Your personal data has successfully updated."
        )
        return super().form_valid(form)

    def form_invalid(self, form: UserModelForm) -> HttpResponse:
        """Adds form error messages and returns redirect to the success_url."""
        for error in form.errors.as_data().values():
            messages.error(self.request, error[0].messages[0])
        return HttpResponseRedirect(self.success_url)


class CustomerDeleteView(
    CustomerPOSTViewMixin, DeleteViewMixin, generic.DeleteView
):
    """View for deleting the customer."""

    success_url = reverse_lazy("shop:home")
    success_message = "Profile has successfully deleted."

lapzone/customer/templates/customer/detail.html
{% extends '_base.html' %} 

{% block title %}Customer profile{% endblock %} 
{% block content_title %}Customer profile - {{ user.username }}{% endblock %}

{% block styles %}
<style>
    @media screen and (max-width: 576px) { /* Bootstrap5 .sm breakpoint */
        .submit-btn { display: flex!important; }
        .form-control.w-50 { width: 100%!important; }
    }
</style>
{% endblock styles %}

{% block to_right_of_content_title %}
<a
    class="btn btn-warning"
    href="{% url 'account_logout' %}"
>
    Log out
</a>
{% endblock to_right_of_content_title %} 


{% block advanced_content %}
<div class="row px-3 d-flex justify-content-between">
    {% include "customer/utils/_link_list_group.html" with page="details" user=user only %}

    <!-- Block with user personal details (form) -->
    <div class="col-lg-9 col-md-12 px-0">
        <div id="content" class="panel-bg-color p-3 rounded">
            <p>
                <b>Date joined:</b> &nbsp; {{ user.date_joined|date:"F d, Y" }}
            </p>

            <form action="{% url 'customer:update' %}" method="post">
                {% csrf_token %}

                {{ form.as_p }}

                <div class="submit-btn my-2 d-block justify-content-center">
                    <input
                        type="submit"
                        value="Update personal info"
                        class="btn btn-success btn-lg"
                    >
                </div>
            </form>
        </div>
    </div>
</div>

<h2 class="my-3">Danger zone</h2>

<div class="row px-3">
    <div 
        class="panel-bg-color p-3 col-12 rounded border border-2 border-danger"
    >
        <h4>Attention!</h4>
        <div class="fs-5">
            <p>
                You are about to permanently delete your account. This action cannot be undone. Your data, including all likes and orders, will be deleted permanently.
            </p>
            <p>
                If you are sure you want to proceed with deleting your account, please click the button below.
            </p>
            <form action="{% url 'customer:delete' %}" method="post">
                {% csrf_token %}

                <input
                    type="submit"
                    value="Delete my account"
                    class="remove btn btn-danger btn-lg mb-3"
                >
            </form>
            <p>
                If you have changed your mind or accidentally clicked this button, you can click the "Cancel" button or simply navigate away from this zone.
            </p>
        </div>
    </div>
</div>
{% endblock advanced_content %}


{% block scripts %}
<!-- Script to disable profile button in the site header -->
<script defer>
    document.querySelector("ion-icon[name='person-circle']").parentElement.href = "#";
</script>
{% load static %}
<script src="{% static 'js/remove_btn.js' %}" defer></script> 
{% endblock scripts %} 

lapzone/customer/templates/customer/wish_list.html
{% extends 'shop/_base.html' %} 

{% block title %}Wish list{% endblock %} 
{% block content_title %}Wish list{% endblock %}


{% block advanced_content %}

{% if not page_obj %}
<div class="mb-5">
    {% include 'utils/_alert.html' with message="Your wish list is empty yet." category="primary" dismissible=False only %}
</div>
{% else %}
<div class="row px-3 mb-5 d-flex justify-content-between">
    {% include "customer/utils/_link_list_group.html" with page="wishes" user=user only %}

    <div class="col-lg-9 col-md-12 px-0">
        <div id="content" class="panel-bg-color p-3 rounded">
            <div id="products" class="row">
            {% for like in page_obj %}
                <div
                    class="col-lg-3 col-md-6 col-sm-12 d-flex align-items-stretch"
                >
                    <div
                        class="product w-100 d-flex flex-column justify-content-between rounded mb-3"
                    >
                        {% include 'shop/utils/_product_card.html' with product=like.product user=user cart=cart.cart only %}
                    </div>
                </div>
            {% endfor %}

            {% if page_obj.paginator.num_pages > 1 %}
                {% include 'utils/_pagination_nav.html' with page_obj=page_obj %}
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock advanced_content %}


{% block scripts %}
{{ block.super }}

{% load static %}
<script defer src="{% static 'js/resize_pagination.js' %}"></script>
<!-- 
    Script for removing the product html element 
    from the page when the user clicks the like button.
-->
<script defer>
    const products = document.getElementById("products");

	document.querySelectorAll(".like").forEach((like_btn) => {
		like_btn.addEventListener("click", function () {
			products.removeChild(
				like_btn.parentElement.parentElement.parentElement
			);
		});
	});
</script>
{% endblock %} 