lapzone/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "cart"
urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="cart/detail.html"),
        name="detail",
    ),
    path("add/", views.CartAddView.as_view()),
    path("update/", views.CartUpdateView.as_view()),
    path("remove/", views.CartRemoveView.as_view()),
]

lapzone/customer/urls.py
from django.urls import path

from . import views


app_name = "customer"
urlpatterns = [
    path("", views.CustomerDetailView.as_view(), name="detail"),
    path("wish-list/", views.CustomerWishListView.as_view(), name="wish_list"),
    path("update/", views.CustomerUpdateView.as_view(), name="update"),
    path("delete/", views.CustomerDeleteView.as_view(), name="delete"),
]

lapzone/lapzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from general.error_views import (
    CustomBadRequestView,
    CustomPermissionDeniedView,
    CustomNotFoundView,
)


handler400 = CustomBadRequestView.as_view()
handler403 = CustomPermissionDeniedView.as_view()
handler404 = CustomNotFoundView.as_view()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("profile/", include("customer.urls")),
    path("mailing/", include("mailing.urls")),
    path(
        "faq/",
        TemplateView.as_view(template_name="pages/FAQs.html"),
        name="faq",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="pages/feedback.html"),
        name="feedback",
    ),
]

if settings.DEBUG and not settings.TESTING:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

lapzone/order/urls.py
from django.urls import path

from . import views


app_name = "order"
urlpatterns = [
    path("list/", views.OrderListView.as_view(), name="list"),
    path("checkout/", views.OrderCheckoutFormView.as_view(), name="create"),
    path("<uuid:pk>/", views.OrderDetailView.as_view(), name="detail"),
    path("<uuid:pk>/delete/", views.OrderDeleteView.as_view(), name="delete"),
]

lapzone/customer/forms.py
from django import forms
from django.contrib.auth.models import User

from general.forms import get_field_widget_attrs_with_placeholder_


class UserModelForm(forms.ModelForm):
    """Form for the User model."""

    def __init__(self, *args, **kwargs) -> None:
        """Initializes the UserModelForm."""
        super().__init__(*args, **kwargs)
        self.fields["username"].help_text = ""
        self.fields["first_name"].required = False
        self.fields["last_name"].required = False

    class Meta:
        """Meta options for the UserModelForm."""

        model = User
        fields = ["username", "first_name", "last_name"]
        widgets = {
            "username": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("Username")
            ),
            "first_name": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("First name")
            ),
            "last_name": forms.TextInput(
                attrs=get_field_widget_attrs_with_placeholder_("Last name")
            ),
        }

lapzone/customer/views.py
from typing import Any
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models.query import QuerySet
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect

from shop.models import Like
from general.views import BaseView, DeleteViewMixin
from .forms import UserModelForm


class CustomerDetailView(BaseView, LoginRequiredMixin, generic.TemplateView):
    """View for the customer detail page."""

    template_name = "customer/detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Adds the UserModelForm to the context and returns it."""
        context: dict[str, Any] = super().get_context_data(**kwargs)
        context["form"] = UserModelForm(instance=self.request.user)
        return context


class CustomerWishListView(BaseView, LoginRequiredMixin, generic.ListView):
    """View for the customer wish list page."""

    paginate_by = 12
    template_name = "customer/wish_list.html"

    def get_queryset(self) -> QuerySet[Like]:
        """Returns the current user's wish list."""
        return self.request.user.like_set.all()


class CustomerPOSTViewMixin(BaseView):
    """Mixin for the "Customer" app POST views."""

    http_method_names = ["post"]

    def get_object(self, queryset: QuerySet[User] | None = None) -> User:
        """Returns the current user."""
        return self.request.user


class CustomerUpdateView(CustomerPOSTViewMixin, generic.UpdateView):
    """View to handle the UserModelForm and update the customer data."""

    model = User
    form_class = UserModelForm
    success_url = reverse_lazy("customer:detail")

    def form_valid(self, form: UserModelForm) -> HttpResponse:
        """Adds a success message and returns the super method."""
        messages.success(
            self.request, "Your personal data has successfully updated."
        )
        return super().form_valid(form)

    def form_invalid(self, form: UserModelForm) -> HttpResponse:
        """Adds form error messages and returns redirect to the success_url."""
        for error in form.errors.as_data().values():
            messages.error(self.request, error[0].messages[0])
        return HttpResponseRedirect(self.success_url)


class CustomerDeleteView(
    CustomerPOSTViewMixin, DeleteViewMixin, generic.DeleteView
):
    """View for deleting the customer."""

    success_url = reverse_lazy("shop:home")
    success_message = "Profile has successfully deleted."

lapzone/customer/templates/customer/utils/_link_list_group.html
<style>
    #content {
        margin-right: 0;
        margin-left: 20px;
    }

    @media screen and (max-width: 992px) {
        /* Bootstrap5 .lg breakpoint */
        #content {
            margin-left: 0;
        }
    }
</style>

<!-- Block with links to other pages -->
<div class="col-lg-3 col-md-12 p-0">
    <div class="list-group">
        <a
            {% if page == 'details' %}aria-current="true"{% endif %}
            href="{% if page == 'details' %}#{% else %}{% url 'customer:detail' %}{% endif %}"
            class="list-group-item list-group-item-action {% if page == 'details' %}active{% endif %}"
        >
            Personal details
        </a>
        <a
            {% if page == 'password' %}aria-current="true"{% endif %}
            href="{% if page == 'password' %}#{% else %}{% url 'account_change_password' %}{% endif %}"
            class="list-group-item list-group-item-action {% if page == 'password' %}active{% endif %}"
        >
            Change password
        </a>
        <a
            {% if page == 'wishes' %}aria-current="true"{% endif %}
            href="{% if page == 'wishes' %}#{% else %}{% url 'customer:wish_list' %}{% endif %}"
            class="list-group-item list-group-item-action content-between {% if page == 'wishes' %}active{% endif %}"
        >
            Wish list
            <span class="badge bg-secondary rounded-pill">
                {{ user.like_set.count }}
            </span>
        </a>
        <a
            {% if page == 'orders' %}aria-current="true"{% endif %}
            href="{% if page == 'orders' %}#{% else %}{% url 'order:list' %}{% endif %}"
            class="list-group-item list-group-item-action content-between {% if page == 'orders' %}active{% endif %}"
        >
            Order list
            <span class="badge bg-secondary rounded-pill">
                {{ user.order_set.count }}
            </span>
        </a>
        <a
            {% if page == 'emails' %}aria-current="true"{% endif %}
            href="{% if page == 'emails' %}#{% else %}{% url 'account_email' %}{% endif %}"
            class="list-group-item list-group-item-action content-between {% if page == 'emails' %}active{% endif %}"
        >
            E-mail addresses
            <span class="badge bg-secondary rounded-pill">
                {{ user.emailaddress_set.count }}
            </span>
        </a>
        <a
            {% if page == 'connections' %}aria-current="true"{% endif %}
            href="{% if page == 'connections' %}#{% else %}{% url 'socialaccount_connections' %}{% endif %}"
            class="list-group-item list-group-item-action content-between {% if page == 'connections' %}active{% endif %}"
        >
            OAuth connections
            <span class="badge bg-secondary rounded-pill">
                {{ user.socialaccount_set.count }}
            </span>
        </a>
    </div>
</div>