lapzone/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "cart"
urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="cart/detail.html"),
        name="detail",
    ),
    path("add/", views.CartAddView.as_view()),
    path("update/", views.CartUpdateView.as_view()),
    path("remove/", views.CartRemoveView.as_view()),
]

lapzone/lapzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from general.error_views import (
    CustomBadRequestView,
    CustomPermissionDeniedView,
    CustomNotFoundView,
)


handler400 = CustomBadRequestView.as_view()
handler403 = CustomPermissionDeniedView.as_view()
handler404 = CustomNotFoundView.as_view()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("profile/", include("customer.urls")),
    path("mailing/", include("mailing.urls")),
    path(
        "faq/",
        TemplateView.as_view(template_name="pages/FAQs.html"),
        name="faq",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="pages/feedback.html"),
        name="feedback",
    ),
]

if settings.DEBUG and not settings.TESTING:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

lapzone/order/urls.py
from django.urls import path

from . import views


app_name = "order"
urlpatterns = [
    path("list/", views.OrderListView.as_view(), name="list"),
    path("checkout/", views.OrderCheckoutFormView.as_view(), name="create"),
    path("<uuid:pk>/", views.OrderDetailView.as_view(), name="detail"),
    path("<uuid:pk>/delete/", views.OrderDeleteView.as_view(), name="delete"),
]

lapzone/shop/urls.py
from django.urls import path

from . import views


app_name = "shop"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "products/", views.AllProductsListView.as_view(), name="product_list"
    ),
    path(
        "category/<slug:slug>/",
        views.ProductListByCategoryView.as_view(),
        name="category",
    ),
    path(
        "brand/<slug:slug>/",
        views.ProductListByBrandView.as_view(),
        name="brand",
    ),
    path(
        "product/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product/<slug:slug>/review/",
        views.ReviewFormView.as_view(),
    ),
    path(
        "product/<slug:slug>/like/",
        views.LikeView.as_view(),
    ),
]

lapzone/cart/views.py
from django.views import generic
from django.http import HttpRequest, HttpResponse

from general.views import BaseView
from . import services


class CartAddView(BaseView, generic.View):
    """View for adding a product to the user's cart via POST request."""

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Returns response message from service adding function."""
        return HttpResponse(
            services.add_product_to_cart_and_get_response_message(request)
        )


class CartUpdateView(BaseView, generic.View):
    """View for updating a product in the user's cart via POST request."""

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Returns response message from service updating function."""
        return HttpResponse(
            services.update_cart_product_and_get_response_message(request)
        )


class CartRemoveView(BaseView, generic.View):
    """View for removing a product from the user's cart via POST request."""

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Returns response message from service removing function."""
        services.remove_product_from_cart(request)
        return HttpResponse(status=200)

lapzone/cart/templates/cart/_base.html
{% extends '_base.html' %} 

{% block styles %}
<style>
    .white-space-nowrap { white-space: nowrap; }
    .white-space-normal { white-space: normal; }

    .table { color: var(--text-color) }
    .table td, .table th { 
        flex: 1; 
        border: 0; 
        text-align: center; 
    }
    .table .image-td { width: 10%; }
    .table img { min-width: 100px; }
    .table input[type="number"] { width: 75px; }
</style>
{% endblock styles %} 

lapzone/cart/templates/cart/detail.html
{% extends 'cart/_base.html' %} 

{% block title %}Cart{% endblock %} 
{% block content_title %}Your shopping cart{% endblock %} 


{% block advanced_content %}

{% if cart|length == 0 %}
    <div class="mb-5">
        {% include 'utils/_alert.html' with message="There are no products in your cart yet." category="primary" dismissible=False only %}
    </div>
{% else %}
{% block order_create_form %}{% endblock %} 

<div class="row px-3 mb-5">
    <div class="panel-bg-color col-12 p-3 rounded">
        {% include 'cart/utils/_product_table.html' with collection=cart app="cart" only %}

        <div class="d-flex justify-content-between fs-4 mt-3">
            <b>Total price: </b>
            <span id="total_price">{{ cart.get_total_price }}$</span>
        </div>

        {% block cart_buttons %} 
        <div class="d-flex justify-content-end mt-4">
            <div>
                <a 
                    href="{% url 'shop:product_list' %}" 
                    class="btn btn-lg btn-primary me-3 mb-2"
                >
                    Continue shopping
                </a>
                <a 
                    href="{% url 'order:create' %}" 
                    class="btn btn-lg btn-success mb-2"
                >
                    Checkout
                </a>
            </div>
        </div>
        {% endblock cart_buttons %}
    </div>
</div>
{% endif %} 

{% endblock advanced_content %}


{% block scripts %}

{% block script_to_disable_cart_btn %} 
<!-- Script to disable cart button in the site header -->
<script defer>
    document.querySelector("ion-icon[name='cart']").parentElement.href = "#";

    // Template variable for fetch "POST" request
    const csrf_token = "{{ csrf_token }}";
</script>
{% endblock script_to_disable_cart_btn %}

{% if cart|length != 0 %}
{% load static %}
<script defer src="{% static 'js/cart/remove_btn.js' %}"></script>
<script defer src="{% static 'js/cart/quantity_field.js' %}"></script>
{% endif %}

{% endblock scripts %} 